// Code generated by "stringer -type=KeyPoint,Section"; DO NOT EDIT.

package court2d

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KP1-0]
	_ = x[KP2-1]
	_ = x[KP3-2]
	_ = x[KP4-3]
	_ = x[KP5-4]
	_ = x[KP6-5]
	_ = x[KP7-6]
	_ = x[KP8-7]
	_ = x[KP9-8]
	_ = x[KP10-9]
	_ = x[KP11-10]
	_ = x[KP12-11]
	_ = x[KP13-12]
	_ = x[KP14-13]
	_ = x[KP15-14]
	_ = x[KP16-15]
	_ = x[KP17-16]
	_ = x[KP18-17]
	_ = x[KP19-18]
	_ = x[KP20-19]
	_ = x[KP21-20]
}

const _KeyPoint_name = "KP1KP2KP3KP4KP5KP6KP7KP8KP9KP10KP11KP12KP13KP14KP15KP16KP17KP18KP19KP20KP21"

var _KeyPoint_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75}

func (i KeyPoint) String() string {
	if i < 0 || i >= KeyPoint(len(_KeyPoint_index)-1) {
		return "KeyPoint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyPoint_name[_KeyPoint_index[i]:_KeyPoint_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FarAdDoublesAlley-0]
	_ = x[FarAdServiceBox-1]
	_ = x[FarBackcourt-2]
	_ = x[FarDeuceDoublesAlley-3]
	_ = x[FarDeuceServiceBox-4]
	_ = x[NearAdDoublesAlley-5]
	_ = x[NearAdServiceBox-6]
	_ = x[NearBackcourt-7]
	_ = x[NearDeuceDoublesAlley-8]
	_ = x[NearDeuceServiceBox-9]
	_ = x[FarSinglesCourt-10]
	_ = x[FarDoublesCourt-11]
	_ = x[NearSinglesCourt-12]
	_ = x[NearDoublesCourt-13]
	_ = x[SinglesCourt-14]
	_ = x[DoublesCourt-15]
}

const _Section_name = "FarAdDoublesAlleyFarAdServiceBoxFarBackcourtFarDeuceDoublesAlleyFarDeuceServiceBoxNearAdDoublesAlleyNearAdServiceBoxNearBackcourtNearDeuceDoublesAlleyNearDeuceServiceBoxFarSinglesCourtFarDoublesCourtNearSinglesCourtNearDoublesCourtSinglesCourtDoublesCourt"

var _Section_index = [...]uint8{0, 17, 32, 44, 64, 82, 100, 116, 129, 150, 169, 184, 199, 215, 231, 243, 255}

func (i Section) String() string {
	if i < 0 || i >= Section(len(_Section_index)-1) {
		return "Section(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Section_name[_Section_index[i]:_Section_index[i+1]]
}
